service:
  name: pdf-lambda-puppeteer

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 5

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal # Modify or remove accordingly
  region: ${opt:region, 'ap-south-1'}
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  getPDF:
    handler: handler.getPDF
    memorySize: 1024 # Setting a higher RAM size to facilitate PDF generation
    events:
      - http:
          method: get
          path: /getPDF
